# Generated by Django 2.1.2 on 2018-10-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20181028_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
