# Generated by Django 2.1.3 on 2018-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOrderPage', '0004_auto_20181107_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredDatetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatchedDatetime',
            field=models.DateTimeField(),
        ),
    ]
