# Generated by Django 2.1.3 on 2018-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOrderPage', '0005_auto_20181107_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
