# Generated by Django 2.1.3 on 2018-11-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Clinic Manager', 'Clinic Manager'), ('Dispatcher', 'Dispatcher'), ('Warehouse Personnel', 'Warehouse Personnel')], max_length=30)),
                ('token', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'Distance',
                'verbose_name_plural': 'Distances',
            },
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Include',
                'verbose_name_plural': 'Includes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('isStartingPoint', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatch', 'Queued for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Queued for Processing', max_length=30)),
                ('priority', models.CharField(choices=[('High', 'high'), ('Medium', 'mid'), ('Low', 'low')], default='Low', max_length=4)),
                ('weight', models.FloatField()),
                ('orderedDatetime', models.DateTimeField()),
                ('dispatchedDatetime', models.DateTimeField(blank=True, null=True)),
                ('deliveredDatetime', models.DateTimeField(blank=True, null=True)),
                ('ordering_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Account')),
                ('ordering_clinic', models.ForeignKey(limit_choices_to={'isStartingPoint': False}, on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
            },
        ),
        migrations.AddField(
            model_name='include',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Order'),
        ),
        migrations.AddField(
            model_name='include',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Supply'),
        ),
        migrations.AddField(
            model_name='distance',
            name='distanceFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location'),
        ),
        migrations.AddField(
            model_name='distance',
            name='distanceTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distanceTo', to='ASP_webApp.Location'),
        ),
        migrations.AddField(
            model_name='account',
            name='worklocation',
            field=models.ForeignKey(limit_choices_to={'isStartingPoint': False}, on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='include',
            unique_together={('order', 'supply')},
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('distanceFrom', 'distanceTo')},
        ),
    ]
