# Generated by Django 2.1.3 on 2018-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatch', 'Queued for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Queued for Processing', max_length=30),
        ),
    ]
