# Generated by Django 2.1.3 on 2018-11-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='worklocation',
            field=models.ForeignKey(limit_choices_to={'isStartingPoint': False}, on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location'),
        ),
    ]
