# Generated by Django 2.1.3 on 2018-11-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='include',
            options={'verbose_name': 'Include', 'verbose_name_plural': 'Includes'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderby',
            options={'verbose_name': 'Order by', 'verbose_name_plural': 'Order by'},
        ),
        migrations.AlterModelOptions(
            name='orderto',
            options={'verbose_name': 'Order to', 'verbose_name_plural': 'Order to'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
        migrations.AddField(
            model_name='location',
            name='isStartingPoint',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveredDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatchedDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('distanceFrom', 'distanceTo')},
        ),
        migrations.AlterUniqueTogether(
            name='orderby',
            unique_together={('order', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='orderto',
            unique_together={('order', 'location')},
        ),
    ]
