# Generated by Django 2.1.3 on 2018-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0002_auto_20181116_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 3), ('Medium', 2), ('Low', 1)], default='Low', max_length=4),
        ),
    ]
