# Generated by Django 2.1.3 on 2018-11-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0002_auto_20181111_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='detail',
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default=123456789, max_length=20),
            preserve_default=False,
        ),
    ]
