# Generated by Django 2.1.3 on 2018-11-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0003_auto_20181111_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordering_clinic',
            field=models.ForeignKey(limit_choices_to={'isStartingPoint': False}, on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location'),
        ),
    ]
