# Generated by Django 2.1.3 on 2018-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0003_auto_20181114_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Queued for Processing', 'queued for processing'), ('Processing by Warehouse', 'processing by warehouse'), ('Queued for Dispatch', 'queued for dispatch'), ('Dispatched', 'dispatched'), ('Delivered', 'delivered')], default='Queued for Processing', max_length=30),
        ),
    ]
