# Generated by Django 2.1.3 on 2018-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0004_auto_20181117_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processedDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
