# Generated by Django 2.1.3 on 2018-11-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0004_auto_20181115_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Clinic Manager', 'clinic manager'), ('Dispatcher', 'dispatcher'), ('Warehouse personnel', 'Warehouse personnel')], max_length=30),
        ),
    ]
