# Generated by Django 2.1.3 on 2018-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0005_order_processeddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 1), ('Medium', 2), ('Low', 3)], default='Low', max_length=10),
        ),
    ]
