# Generated by Django 2.1.3 on 2018-11-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0005_auto_20181115_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Clinic Manager', 'Clinic Manager'), ('Dispatcher', 'Dispatcher'), ('Warehouse Personnel', 'Warehouse Personnel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatch', 'Queued for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Queued for Processing', max_length=30),
        ),
    ]
