# Generated by Django 2.1.3 on 2018-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0006_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatched', 'Queued for Dispatched'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Queued for Processing', max_length=30),
        ),
    ]
