# Generated by Django 2.1.3 on 2018-11-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0007_auto_20181120_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='worklocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location'),
        ),
    ]
