# Generated by Django 2.1.3 on 2018-11-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0008_auto_20181130_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Clinic Manager', 'Clinic Manager'), ('Dispatcher', 'Dispatcher'), ('Warehouse Personnel', 'Warehouse Personnel'), ('Admin', 'Admin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='worklocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ASP_webApp.Location'),
        ),
    ]
