# Generated by Django 2.1.3 on 2018-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASP_webApp', '0009_auto_20181130_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default='Low', max_length=10),
        ),
    ]
