# Generated by Django 2.1.2 on 2018-10-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0003_distance_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
