# Generated by Django 2.1.1 on 2018-11-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0009_auto_20181106_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CMid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.CMAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderby',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.CMAccount'),
        ),
    ]
