# Generated by Django 2.1.3 on 2018-11-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0010_auto_20181107_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dispatcheraccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='whpaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='cmaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.Account'),
        ),
        migrations.AlterField(
            model_name='dispatcheraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.Account'),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.Order'),
        ),
        migrations.AlterField(
            model_name='orderto',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.Order'),
        ),
        migrations.AlterField(
            model_name='whpaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='include',
            unique_together={('order', 'supply')},
        ),
    ]
