# Generated by Django 2.1.3 on 2018-11-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0012_auto_20181107_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 'high'), ('Medium', 'mid'), ('Low', 'low')], default='Low', max_length=6),
        ),
    ]
