# Generated by Django 2.1.2 on 2018-10-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_account_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='include',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
