# Generated by Django 2.1.2 on 2018-10-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_include_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 'high'), ('Medium', 'mid'), ('Low', 'low')], default='Low', max_length=4),
        ),
    ]
