# Generated by Django 2.1.2 on 2018-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='weight',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
