# Generated by Django 2.1.1 on 2018-11-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20181105_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HAAccount',
            new_name='CMAccount',
        ),
        migrations.RenameModel(
            old_name='PackerAccount',
            new_name='WHPAccount',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ordering_clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.Location'),
            preserve_default=False,
        ),
    ]
