# Generated by Django 2.1.3 on 2018-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20181107_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatchedDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
